# Generated by Django 4.2.3 on 2025-12-11 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import organizations.fields
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(help_text='The name of the organization', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('slug', organizations.fields.SlugField(blank=True, editable=False, help_text='The name in all lowercase, suitable for URL identification', max_length=200, populate_from='name', unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hierarchy_level', models.CharField(choices=[('AG', 'Agency'), ('Dir', 'Direction'), ('DG', 'General Direction')], max_length=3)),
                ('sub_name', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('billing_template_choice', models.CharField(choices=[('template1', 'Billing template 1'), ('template2', 'Billing template 2')], default='template1', max_length=50)),
                ('street_address', models.CharField(default='', max_length=100)),
                ('contact_number', models.CharField(default='', max_length=20)),
                ('short_name', models.CharField(default='', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate in the following format: 00.00%', max_digits=4)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=30)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Africa/Douala')),
                ('contribuable', models.CharField(blank=True, help_text='This field is Optional', max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='distrivite/images')),
                ('credential', models.CharField(max_length=20, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'permissions': [('view_organizationdashboard', 'Can view organization dashboard')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('guid', models.UUIDField(editable=False)),
                ('invitee_identifier', models.CharField(help_text='The contact identifier for the invitee, email, phone number, social media handle, etc.', max_length=1000)),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='pending', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationOwner',
            fields=[
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'organization owner',
                'verbose_name_plural': 'organization owners',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_device', models.BooleanField(default=False)),
                ('is_gps_active', models.BooleanField(default=False)),
                ('is_liveness_active', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('can_edit_price', models.BooleanField(default=False)),
                ('can_print_transaction', models.BooleanField(default=False)),
                ('can_print_bill', models.BooleanField(default=False)),
                ('embeddings', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'organization user',
                'verbose_name_plural': 'organization users',
                'ordering': ['organization', 'user'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUserGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_user_groups', to='organization.organizationgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_user_groups', to='organization.organizationuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The organization groups this user belongs to. A user will get all permissions granted to each of their groups.', through='organization.OrganizationUserGroup', to='organization.organizationgroup', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this organization user.', to='auth.permission', verbose_name='organization user permissions'),
        ),
    ]
