# Generated by Django 4.2.3 on 2025-12-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='organization.organizationuser'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='stock',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='orders.batch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='stock',
            name='organization_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='organization.organizationuser'),
        ),
        migrations.AddField(
            model_name='prepaidaccount',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.customer'),
        ),
        migrations.AddField(
            model_name='prepaidaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='facturationstock',
            name='facturation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturation_stocks', to='orders.facturation'),
        ),
        migrations.AddField(
            model_name='facturationstock',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='facturationstock',
            name='organization_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organizationuser'),
        ),
        migrations.AddField(
            model_name='facturationstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturation_stocks', to='orders.stock'),
        ),
        migrations.AddField(
            model_name='facturationrefund',
            name='facturation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturation_FacturationRefunds', to='orders.facturation'),
        ),
        migrations.AddField(
            model_name='facturationrefund',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturation_FacturationRefunds', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='facturationrefund',
            name='organization_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturation_FacturationRefunds', to='organization.organizationuser'),
        ),
        migrations.AddField(
            model_name='facturationpayment',
            name='facturation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturation_payments', to='orders.facturation'),
        ),
        migrations.AddField(
            model_name='facturationpayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturation_payments', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='facturationpayment',
            name='organization_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturation_payments', to='organization.organizationuser'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturations', to='orders.customer'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='organization_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organizationuser'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='organization_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationuser'),
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='batch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchs', to='orders.item'),
        ),
        migrations.AddField(
            model_name='batch',
            name='last_maintainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organizationuser'),
        ),
        migrations.AddField(
            model_name='batch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchs', to='orders.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='facturationstock',
            unique_together={('organization', 'facturation', 'stock')},
        ),
        migrations.AlterUniqueTogether(
            name='facturationrefund',
            unique_together={('organization', 'bill_number')},
        ),
        migrations.AlterUniqueTogether(
            name='commercial',
            unique_together={('organization', 'organization_user')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name')},
        ),
    ]
