# Generated by Django 4.2.3 on 2025-12-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturationpayment',
            name='transaction_broker',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('orange_money', 'Orange Money'), ('mtn_mobile_money', 'MTN Mobile Money')], default='cashier', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_broker',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('orange_money', 'Orange Money'), ('mtn_mobile_money', 'MTN Mobile Money')], default='cashier', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit')], max_length=20),
        ),
    ]
