# Generated by Django 4.2.3 on 2025-12-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepaidaccount',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='prepaidaccount',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Commercial',
        ),
        migrations.DeleteModel(
            name='PrepaidAccount',
        ),
    ]
