# Generated by Django 4.2.3 on 2025-12-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('orders', '0003_alter_facturationpayment_transaction_broker_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('organization', 'organization_user', 'batch')},
        ),
    ]
