# Generated by Django 4.2.3 on 2025-12-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacturationPayment',
        ),
    ]
