# Generated by Django 4.2.3 on 2025-12-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
