# Generated by Django 4.2.3 on 2025-12-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('orders', '0004_delete_facturationpayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacturationPayment2',
            new_name='FacturationPayment',
        ),
    ]
