# Generated by Django 4.2.3 on 2025-12-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('orders', '0005_rename_facturationpayment2_facturationpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturationpayment',
            name='facturation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturation_payments', to='orders.facturation'),
        ),
        migrations.AlterField(
            model_name='facturationpayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturation_payments', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='facturationpayment',
            name='organization_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturation_payments', to='organization.organizationuser'),
        ),
    ]
