# Generated by Django 4.2 on 2025-12-17 19:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_stock_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
