# Generated by Django 4.2.3 on 2025-12-18 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('orders', '0006_customer_credit_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCreditPayment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_broker', models.CharField(choices=[('cashier', 'Cashier'), ('orange_money', 'Orange Money'), ('mtn_mobile_money', 'MTN Mobile Money')], default='cashier', max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=19)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_credit_payments', to='orders.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_credit_payments', to='organization.organization')),
                ('organization_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_credit_payments', to='organization.organizationuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
