# Generated by Django 4.2.3 on 2025-12-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_facturationpayment_facturation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturation',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='facturation',
            name='is_pay',
        ),
    ]
