# Generated by Django 4.2.3 on 2025-12-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_bulkcreditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturationpayment',
            name='bulk_credit_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturation_payments', to='orders.bulkcreditpayment'),
        ),
    ]
