# Generated by Django 4.2.3 on 2025-12-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_facturation_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturationstock',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
