# Generated by Django 4.2.3 on 2025-12-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_facturationpayment_bulk_credit_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturation',
            options={'permissions': [('deliver_facturation', 'Can deliver facturation'), ('print_facturation', 'Can print facturation')]},
        ),
        migrations.AlterModelOptions(
            name='facturationstock',
            options={'permissions': [('deliver_facturationstock', 'Can deliver facturation stock')]},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'permissions': [('change_stockprice', 'Can change stock price')]},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('print_transaction', 'Can print transaction')]},
        ),
    ]
