# Generated by Django 4.2.3 on 2025-12-25 16:08

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_facturation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkcreditpayment",
            name="bill_number",
            field=apps.core.fields.ProfessionalBillNumberField(
                default=21, max_length=20
            ),
            preserve_default=False,
        ),
    ]
