# Generated by Django 4.2.3 on 2025-12-26 12:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_bulkcreditpayment_bill_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="prepaid_amount",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
    ]
