from django.urls import path

from . import views

app_name = "cashflow"

urlpatterns = [
    path(
        "categorys/",
        views.OrgCategoryListView.as_view(),
        name="category_list",
    ),
    path(
        "categorys/add/",
        views.OrgCategoryAddView.as_view(),
        name="category_add",
    ),
    path(
        "categorys/<uuid:pk>/",
        views.OrgCategoryDetailView.as_view(),
        name="category_detail",
    ),
    path(
        "categorys/<uuid:pk>/change/",
        views.OrgCategoryChangeView.as_view(),
        name="category_change",
    ),
    path(
        "categorys/<uuid:pk>/delete/",
        views.OrgCategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path(
        "withdrawals/<uuid:pk>/receipt/",
        views.OrgExpenseReceiptView.as_view(),
        name="withdrawal_receipt",
    ),
    path(
        "cash_registers/",
        views.OrgCashRegisterListView.as_view(),
        name="cash_register_list",
    ),
    path(
        "cash_registers/add/",
        views.OrgCashRegisterCreateView.as_view(),
        name="cash_register_add",
    ),
    path(
        "cash_registers/<uuid:pk>/",
        views.OrgCashRegisterDetailView.as_view(),
        name="cash_register_detail",
    ),
    path(
        "cash_registers/<uuid:pk>/change/",
        views.OrgCashRegisterUpdateView.as_view(),
        name="cash_register_change",
    ),
    path(
        "cash_registers/<uuid:pk>/delete/",
        views.OrgCashRegisterDeleteView.as_view(),
        name="cash_register_delete",
    ),
    path(
        "deposits/",
        views.OrgDepositListView.as_view(),
        name="deposit_list",
    ),
    path(
        "transactions/",
        views.OrgTransactionListView.as_view(),
        name="transaction_list",
    ),
    path(
        "deposits/add/",
        views.OrgDepositCreateView.as_view(),
        name="deposit_add",
    ),
    path(
        "deposits/<uuid:pk>/change/",
        views.OrgDepositUpdateView.as_view(),
        name="deposit_change",
    ),
    path(
        "deposits/<uuid:pk>/",
        views.OrgDepositDetailView.as_view(),
        name="deposit_detail",
    ),
    path(
        "deposits/<uuid:pk>/delete/",
        views.OrgDepositDeleteView.as_view(),
        name="deposit_delete",
    ),
    path(
        "expenses/",
        views.OrgWithdrawalListView.as_view(),
        name="withdrawal_list",
    ),
    path(
        "expenses/print/",
        views.OrgPrintWithdrawalListView.as_view(),
        name="withdrawal_list_print",
    ),
    path(
        "deposits/print/",
        views.OrgPrintDepositListView.as_view(),
        name="deposit_list_print",
    ),
    path(
        "expenses/add/",
        views.OrgWithdrawalCreateView.as_view(),
        name="withdrawal_add",
    ),
    path(
        "expenses/<uuid:pk>/change/",
        views.OrgWithdrawalUpdateView.as_view(),
        name="withdrawal_change",
    ),
    path(
        "expenses/<uuid:pk>/",
        views.OrgWithdrawalDetailView.as_view(),
        name="withdrawal_detail",
    ),
    path(
        "expenses/<uuid:pk>/delete/",
        views.OrgWithdrawalDeleteView.as_view(),
        name="withdrawal_delete",
    ),
    path(
        "withdrawals/<uuid:pk>/validated/",
        views.OrgWithdrawalFinishedView.as_view(),
        name="withdrawal_validated",
    ),
    path(
        "deposits/<uuid:pk>/receipt/",
        views.OrgDepositReceiptView.as_view(),
        name="deposit_receipt",
    ),
    path(
        "cash_registers/<uuid:cash_register>/transactions/",
        views.OrgTransactionListView.as_view(),
        name="transaction_list",
    ),
    path(
        "transactions/print/",
        views.OrgPrintTransactionListView.as_view(),
        name="transaction_list_print",
    ),
]
