# Generated by Django 4.2.3 on 2025-12-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashflow', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_users', to='organization.organizationuser'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cashflow.category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='cashregister',
            unique_together={('organization', 'name')},
        ),
    ]
