from django.urls import path

from . import views

app_name = "orders"

urlpatterns = [
    path(
        "customers/",
        views.OrgCustomerListView.as_view(),
        name="customer_list",
    ),
    path(
        "customers/add/",
        views.OrgCustomerAddView.as_view(),
        name="customer_add",
    ),
    path(
        "customers/<uuid:pk>/change/",
        views.OrgCustomerChangeView.as_view(),
        name="customer_change",
    ),
    path(
        "customers/<uuid:pk>/",
        views.OrgCustomerDetailView.as_view(),
        name="customer_detail",
    ),
    path(
        "customers/<uuid:pk>/delete/",
        views.OrgCustomerDeleteView.as_view(),
        name="customer_delete",
    ),
    path(
        "items/",
        views.OrgItemListView.as_view(),
        name="item_list",
    ),
    path(
        "items/add/",
        views.OrgItemAddView.as_view(),
        name="item_add",
    ),
    path(
        "items/<uuid:pk>/change/",
        views.OrgItemChangeView.as_view(),
        name="item_change",
    ),
    path(
        "items/<uuid:pk>/",
        views.OrgItemDetailView.as_view(),
        name="item_detail",
    ),
    path(
        "items/<uuid:pk>/delete/",
        views.OrgItemDeleteView.as_view(),
        name="item_delete",
    ),
    path(
        "stocks/",
        views.OrgStockListView.as_view(),
        name="stock_list",
    ),
    path(
        "stocks/add/",
        views.OrgStockAddView.as_view(),
        name="stock_add",
    ),
    path(
        "stocks/<uuid:pk>/change/",
        views.OrgStockChangeView.as_view(),
        name="stock_change",
    ),
    path(
        "stocks/<uuid:pk>/",
        views.OrgStockDetailView.as_view(),
        name="stock_detail",
    ),
    path(
        "stocks/<uuid:pk>/delete/",
        views.OrgStockDeleteView.as_view(),
        name="stock_delete",
    ),
    path(
        "batchs/",
        views.OrgBatchListView.as_view(),
        name="batch_list",
    ),
    path(
        "batchs/add/",
        views.OrgBatchAddView.as_view(),
        name="batch_add",
    ),
    path(
        "batchs/<uuid:pk>/change/",
        views.OrgBatchChangeView.as_view(),
        name="batch_change",
    ),
    path(
        "batchs/<uuid:pk>/",
        views.OrgBatchDetailView.as_view(),
        name="batch_detail",
    ),
    path(
        "batchs/<uuid:pk>/delete/",
        views.OrgBatchDeleteView.as_view(),
        name="batch_delete",
    ),
    path(
        "suppliers/",
        views.OrgSupplierListView.as_view(),
        name="supplier_list",
    ),
    path(
        "suppliers/add/",
        views.OrgSupplierAddView.as_view(),
        name="supplier_add",
    ),
    path(
        "suppliers/<uuid:pk>/change/",
        views.OrgSupplierChangeView.as_view(),
        name="supplier_change",
    ),
    path(
        "suppliers/<uuid:pk>/",
        views.OrgSupplierDetailView.as_view(),
        name="supplier_detail",
    ),
    path(
        "suppliers/<uuid:pk>/delete/",
        views.OrgSupplierDeleteView.as_view(),
        name="supplier_delete",
    ),
    path(
        "categories/",
        views.OrgCategoryListView.as_view(),
        name="category_list",
    ),
    path(
        "categories/add/",
        views.OrgCategoryAddView.as_view(),
        name="category_add",
    ),
    path(
        "categories/<uuid:pk>/change/",
        views.OrgCategoryChangeView.as_view(),
        name="category_change",
    ),
    path(
        "categories/<uuid:pk>/",
        views.OrgCategoryDetailView.as_view(),
        name="category_detail",
    ),
    path(
        "categories/<uuid:pk>/delete/",
        views.OrgCategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path(
        "facturations/",
        views.OrgFacturationListView.as_view(),
        name="facturation_list",
    ),
    path(
        "facturations/add/",
        views.OrgFacturationAddView.as_view(),
        name="facturation_add",
    ),
    path(
        "facturations/<uuid:pk>/change/",
        views.OrgFacturationChangeView.as_view(),
        name="facturation_change",
    ),
    path(
        "facturations/<uuid:pk>/",
        views.OrgFacturationDetailView.as_view(),
        name="facturation_detail",
    ),
    path(
        "facturations/<uuid:pk>/delete/",
        views.OrgFacturationDeleteView.as_view(),
        name="facturation_delete",
    ),
    path(
        "facturations/<uuid:pk>/deliver",
        views.OrgFacturationDeliverView.as_view(),
        name="facturation_deliver",
    ),
    path(
        "facturations/<uuid:pk>/approved/",
        views.OrgFacturationApprovedView.as_view(),
        name="facturation_approved",
    ),
    path(
        "facturations/<uuid:pk>/receipt/",
        views.OrgFacturationReceiptView.as_view(),
        name="facturation_receipt",
    ),
    path(
        "facturations/<uuid:pk>/receipt_matrix/",
        views.OrgFacturationReceiptMatrixPrinterView.as_view(),
        name="facturation_receipt_matrix",
    ),
    path(
        "facturations/<uuid:pk>/proforma/",
        views.OrgFacturationProformaView.as_view(),
        name="facturation_proforma",
    ),
    path(
        "facturations/<uuid:pk>/mini-receipt/",
        views.OrgFacturationThermalReceiptView.as_view(),
        name="facturation_mini_receipt",
    ),
    path(
        "facturations/<uuid:facturation>/stocks/",
        views.OrgFacturationStockListView.as_view(),
        name="facturation_stock_list",
    ),
    path(
        "facturations/<uuid:facturation>/stocks/add/",
        views.OrgFacturationStockCreateView.as_view(),
        name="facturation_stock_add",
    ),
    path(
        "facturations/<uuid:facturation>/stocks/<uuid:pk>/change/",
        views.OrgFacturationStockUpdateView.as_view(),
        name="facturation_stock_change",
    ),
    path(
        "facturations/<uuid:facturation>/stocks/<uuid:pk>/detail/",
        views.OrgFacturationStockDetailView.as_view(),
        name="facturation_stock_detail",
    ),
    path(
        "facturations/<uuid:facturation>/stocks/<uuid:pk>/delete/",
        views.OrgFacturationStockDeleteView.as_view(),
        name="facturation_stock_delete",
    ),
    path(
        "facturations/<uuid:facturation>/payments/",
        views.OrgFacturationPaymentListView.as_view(),
        name="facturation_payment_list",
    ),
    path(
        "facturations/<uuid:facturation>/payments/add/",
        views.OrgFacturationPaymentCreateView.as_view(),
        name="facturation_payment_add",
    ),
    path(
        "facturations/<uuid:facturation>/payments/<uuid:pk>/change/",
        views.OrgFacturationPaymentUpdateView.as_view(),
        name="facturation_payment_change",
    ),
    path(
        "facturations/<uuid:facturation>/payments/<uuid:pk>/detail/",
        views.OrgFacturationPaymentDetailView.as_view(),
        name="facturation_payment_detail",
    ),
    path(
        "facturations/<uuid:facturation>/payments/<uuid:pk>/delete/",
        views.OrgFacturationPaymentDeleteView.as_view(),
        name="facturation_payment_delete",
    ),
    path(
        "facturations/<uuid:facturation>/refunds/",
        views.OrgFacturationRefundListView.as_view(),
        name="facturation_refund_list",
    ),
    path(
        "facturations/<uuid:facturation>/refunds/add/",
        views.OrgFacturationRefundCreateView.as_view(),
        name="facturation_refund_add",
    ),
    path(
        "facturations/<uuid:facturation>/refunds/<uuid:pk>/change/",
        views.OrgFacturationRefundUpdateView.as_view(),
        name="facturation_refund_change",
    ),
    path(
        "facturations/<uuid:facturation>/refunds/<uuid:pk>/detail/",
        views.OrgFacturationRefundDetailView.as_view(),
        name="facturation_refund_detail",
    ),
    path(
        "facturations/<uuid:facturation>/refunds/<uuid:pk>/delete/",
        views.OrgFacturationRefundDeleteView.as_view(),
        name="facturation_refund_delete",
    ),
    path(
        "transactions/",
        views.OrgTransactionListView.as_view(),
        name="transaction_list",
    ),
    path(
        "transactions/add/",
        views.OrgTransactionAddView.as_view(),
        name="transaction_add",
    ),
    path(
        "transactions/transactions/<uuid:pk>/change/",
        views.OrgTransactionChangeView.as_view(),
        name="transaction_change",
    ),
    path(
        "transactions/<uuid:pk>/delete/",
        views.OrgTransactionDeleteView.as_view(),
        name="transaction_delete",
    ),
    path(
        "transactions/<uuid:pk>/detail/",
        views.OrgTransactionDetailView.as_view(),
        name="transaction_detail",
    ),
    path(
        "bulk-credit-payments/",
        views.OrgBulkCreditPaymentListView.as_view(),
        name="bulk_credit_payment_list",
    ),
    path(
        "bulk-credit-payments/add/",
        views.OrgBulkCreditPaymentCreateView.as_view(),
        name="bulk_credit_payment_add",
    ),
    path(
        "bulk-credit-payments/<uuid:pk>/change/",
        views.OrgBulkCreditPaymentUpdateView.as_view(),
        name="bulk_credit_payment_change",
    ),
    path(
        "bulk-credit-payments/<uuid:pk>/detail/",
        views.OrgBulkCreditPaymentDetailView.as_view(),
        name="bulk_credit_payment_detail",
    ),
    path(
        "bulk-credit-payments/<uuid:pk>/delete/",
        views.OrgBulkCreditPaymentDeleteView.as_view(),
        name="bulk_credit_payment_delete",
    ),
]
